### ISSUE TITLE
marked smartpants option is always enabled regardless languages

### ISSUE THREAD

**Issue by cwang22** [myst729/Vuelog#15]
https://github.com/myst729/Vuelog/blob/master/src/components/VuelogRenderer.vue#L182

As the title said, this results in all apostrophe are replaced by quotation marks.

**Comment by myst729** [comment]
@cwang22 

I don't think this is an issue. It's more of an opinion based decision.

What problem did you encountered with it? If you think it should be a configurable option, contribution is welcome. 😃
