### ISSUE TITLE
add getting started instructions

### ISSUE THREAD

**Issue by connor11528** [myst729/Vuelog#17]
Is there a starter template like vue cli for the project or can we integrate vuelog into vue-cli apps?

I see that there are download links. Does this mean the usual workflow to start a new vuelog project is to clone this entire repository or is there a template with the files described in the [file structure](https://vuelog.js.org/#/blog/docs/2016/file-structure-of-vuelog) section?

**Comment by myst729** [comment]
This repo is for developers who want to add features to Vuelog or fix bugs. If you just want to have a blog and write something, download the package, extract, then start to write. The package is the docs of the project, it's also the template.

**Comment by connor11528** [comment]
Okay that's fair. carry on, carry on
