### ISSUE TITLE
hosting on github pages

### ISSUE THREAD

**Issue by connor11528** [myst729/Vuelog#19]
I have a repo here for building a blog: https://github.com/connor11528/vuelog-starter/tree/gh-pages

I have pushed the repo up to a new `gh-pages` branch and set the base in my **database.js** file.

```
    // Path to the domain root that serves your site, starts and ends with slash (`/`).
    // Set to `'/'` if your site is under domain root.
    base: '/vuelog-starter/', 
```

I then ran `yarn build`

When I push up the code the website shows a `Loading...` page instead of the compiled application.  It looks like the full static build is hosted in the `docs` folder.

How do I render my vuelog blog on gh-pages?

**Comment by myst729** [comment]
The release package is for deployment. Extract it and push to your **gh-pages** branch, that's it. The repo is not for hosting, it's for developers.
