### ISSUE TITLE
Blog Content Crawlable

### ISSUE THREAD

**Issue by menteora** [myst729/Vuelog#20]
Hi Leo,
thank you for your interesting project. 

I have a doubt. Is your content crawlable from google search?
I see you use :marked estension to load dinamically from client .md files.

Source of my question: https://webmasters.googleblog.com/2016/11/building-indexable-progressive-web-apps.html

Thank you for your attention.

**Comment by myst729** [comment]
Honestly, I don't care about SEO in this project. But if you search **vuelog.js.org** in Google, you'll find that Google can crawl client generated content, amazing. However, if you do concern better ranking, I'd suggest Hexo or Jekyll.
