### ISSUE TITLE
Dependencies內有angular?

### ISSUE THREAD

**Issue by CodinCat** [myst729/Vuelog#3]
`package.json` : line 20
是否為誤植呢？

**Comment by myst729** [comment]
Angular 和 jQuery 都是 algoliasearch/autocomplete.js 的依赖。它提供了原生、Angular、jQuery 三种调用方式，所以强行引入了这两个依赖包。但我肯定会选择原生，而不是 Angular 或 jQuery 的调用方式。因此不用担心，这两个实际上没有被用到的依赖包会在构建过程中被筛掉，并不会增加构建版本的大小。（由此可见 algoliasearch/autocomplete.js 代码挺糟糕的……
