### ISSUE TITLE
Prismjs with color theme option

### ISSUE THREAD

**Issue by ocampogeric** [myst729/Vuelog#30]
Hi @myst729, I'm trying to add multi theme support in Vuelog by defined database.js attribute, but I can't get it work.

I tried with `import` css, and doesn't work. 
Can you say me, where you define de default theme? I can't understand :cry: 

P.S. I notice you change highlight to prismjs, I use in my personal site 2.11.1 and in that case I change styles directly, but now I want add  this option by attribute.

**Comment by ocampogeric** [comment]
I read about [babel-plugin-prismjs](https://github.com/mAAdhaTTah/babel-plugin-prismjs) but I can't get it work. :(

**Comment by myst729** [comment]
https://github.com/myst729/Vuelog/blob/master/src/components/VuelogRenderer.vue#L150

**Comment by myst729** [comment]
Code highlighting styles are hard-coded.

https://github.com/myst729/Vuelog/blob/master/src/assets/styles/highlight.styl

I didn't think of making it themable in the beginning. This might be a good amount of work.
