### ISSUE TITLE
Running dev-server on different host/port?

### ISSUE THREAD

**Issue by bravo-kernel** [myst729/Vuelog#31]
Adding this as a note for future visitors. To change the host and/or port start the development server using one of the following commands:

```bash
# different host only
npm run dev -- --host 0.0.0.0

# different port only
npm run dev -- --port 8086

# different host and port
npm run dev -- --host 0.0.0.0 --port 8086
```

**Comment by bravo-kernel** [comment]
To prevent `Invalid Host Header` error message also set `disableHostCheck` option in `build/webpack.dev.conf.js` to `true`: 

```js
    devServer: {
        disableHostCheck: true,
        // other options
    }
```l

**Comment by bravo-kernel** [comment]
I would prefer not having to change `webpack.dev.conf.js`. Any suggestions? The 0.0.0.0 is needed for e.g. running inside Vagrant virtual machines.

**Comment by myst729** [comment]
This project is generated from [vuejs-templates/webpack](https://github.com/vuejs-templates/webpack). Your request might be better go there. For this repo, just fork and modify at your desire.
