### ISSUE TITLE
# in URL and SEO 

### ISSUE THREAD

**Issue by OualiS** [myst729/Vuelog#35]
Hey thank's for the back end it's very usefull !
But i have a question, we got url like .../#/home/... is that not a problem for good SEO ?

Thank's again :)

**Comment by myst729** [comment]
SEO is not in the list of considerations.

https://github.com/myst729/Vuelog/issues/13#issuecomment-277411895
https://github.com/myst729/Vuelog/issues/20#issuecomment-331814998

Hexo, Jekyll or other static site generator may better fit your needs.

**Comment by OualiS** [comment]
Alright, thank you for you answer i'll try with your framework first and if it's doesn't work good i'll change but as you said google seems like to like your :)
